Bound = 3
StartLen = 1
Speed = 1000
CanHitWall = true
UseBorder = false
CanSpeedUp = true
UseSpeed = false
UseAcceleration = false
UseLevel = false
[Level]
Threshold = 5
DefLevel = 0
Levels = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5]
[TileSet]
None = "·"
Body = "○"
Head = "●"
Crate = "▲"
Wall = "▣"
