
[Gameplay]
StartingLength = 1
CanPassWall = true
UseLevel = false

[GameplayLevel]
Threshold = 5
DefaultLevel = 0
Levels = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5]

[GameplayMotor]
MotorType = 1
StartingSpeed = 1000
UseLevelAccelerator = false

[Visual]
UseBorder = false
UseDashboard = true

[VisualMap]
SideLength = 10
None = "·"
Body = "○"
Head = "●"
Crate = "▲"
Wall = "▣"
