Bound = 10
StartLen = 1
Speed = 1000
CanHitWall = true
UseBorder = false
CanMarchByKey = true
CanMarchByTimer = true
UseAcceleration = true
UseLevel = false
UseDashboard = true

[Level]
Threshold = 5
DefaultLevel = 0
Levels = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5]

[TileSet]
None = "·"
Body = "○"
Head = "●"
Crate = "▲"
Wall = "▣"
